ALTER TABLE COMMENT
DROP
CONSTRAINT FK7MGS5NQ3KJMU06S9BM6QEFIA9;

ALTER TABLE COMMENT
DROP
CONSTRAINT FKQM52P1V3O13HY268HE0WCNGR5;

CREATE TABLE comments
(
    id           UUID         NOT NULL,
    isi_komentar VARCHAR(255) NOT NULL,
    bacaan_id    UUID,
    user_id      BIGINT,
    created_at   TIMESTAMP    NOT NULL,
    parent_id    UUID,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_BACAAN FOREIGN KEY (bacaan_id) REFERENCES bacaan (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES comments (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE COMMENT CASCADE;