ALTER TABLE clan_group
    ADD COLUMN IF NOT EXISTS current_league VARCHAR(20) NOT NULL DEFAULT 'BRONZE';

ALTER TABLE clan_group
    ADD COLUMN IF NOT EXISTS current_season_points BIGINT NOT NULL DEFAULT 0;

ALTER TABLE clan_group
    ADD COLUMN IF NOT EXISTS last_season_rank INT;

CREATE TABLE IF NOT EXISTS league_season_state
(
    id                BIGINT PRIMARY KEY,
    season_number     INT         NOT NULL,
    status            VARCHAR(20) NOT NULL,
    last_processed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clan_season_result
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_number  INT         NOT NULL,
    clan_id        BIGINT      NOT NULL,
    league_before  VARCHAR(20) NOT NULL,
    league_after   VARCHAR(20) NOT NULL,
    rank_in_league INT         NOT NULL,
    points         BIGINT      NOT NULL,
    promoted       BOOLEAN     NOT NULL DEFAULT FALSE,
    relegated      BOOLEAN     NOT NULL DEFAULT FALSE,
    season_winner  BOOLEAN     NOT NULL DEFAULT FALSE,
    processed_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
