ALTER TABLE USER_ACHIEVEMENT
    DROP CONSTRAINT FK5HQ4MS9IKRXW18TF1WN12ANJ6;

ALTER TABLE COMMENT
    DROP CONSTRAINT FK7MGS5NQ3KJMU06S9BM6QEFIA9;

ALTER TABLE CLAN_GROUP
    DROP CONSTRAINT FKAB6JK3EFX0Y9FUF15M9H3OHXP;

ALTER TABLE CLAN_MEMBER
    DROP CONSTRAINT FKG5LFLX5TQ4CVM25QP9CN2EB5F;

ALTER TABLE COMMENT
    DROP CONSTRAINT FKQM52P1V3O13HY268HE0WCNGR5;

CREATE TABLE app_users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(20)                             NOT NULL,
    display_name VARCHAR(50)                             NOT NULL,
    email        VARCHAR(100),
    phone_number VARCHAR(20),
    password     VARCHAR(255),
    role         VARCHAR(10)                             NOT NULL,
    provider     VARCHAR(10),
    provider_id  VARCHAR(100),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id           UUID         NOT NULL,
    isi_komentar VARCHAR(255) NOT NULL,
    bacaan_id    UUID,
    user_id      BIGINT,
    created_at   TIMESTAMP    NOT NULL,
    parent_id    UUID,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_email UNIQUE (email);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_phone_number UNIQUE (phone_number);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_username UNIQUE (username);

ALTER TABLE clan_group
    ADD CONSTRAINT FK_CLAN_GROUP_ON_OWNER FOREIGN KEY (owner_id) REFERENCES app_users (id);

ALTER TABLE clan_member
    ADD CONSTRAINT FK_CLAN_MEMBER_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_BACAAN FOREIGN KEY (bacaan_id) REFERENCES bacaan (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES comments (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE user_achievement
    ADD CONSTRAINT FK_USERACHIEVEMENT_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

DROP TABLE COMMENT CASCADE;

DROP TABLE USERS CASCADE;