ALTER TABLE achievement
    ADD COLUMN IF NOT EXISTS milestone INTEGER NOT NULL DEFAULT 1;

UPDATE achievement
SET milestone = 1
WHERE name = 'First Read';

UPDATE achievement
SET description = 'Selesaikan 1 bacaan pertama Anda.'
WHERE name = 'First Read'
  AND (description IS NULL OR description = 'Selesaikan kuis pertama kali.');

CREATE TABLE IF NOT EXISTS daily_mission
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    milestone    INTEGER      NOT NULL,
    mission_date DATE         NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_completed_reading
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT    NOT NULL,
    bacaan_id    UUID      NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_user_completed_reading UNIQUE (user_id, bacaan_id)
);